### ISSUE TITLE
Can't seem to summon Nexus VR Backpack with Enigma active

### ISSUE THREAD

**Issue by noblereign** [TheNexusAvenger/Nexus-VR-Backpack#1]
wasn't quite sure where to report this (enigma? nexus vr character? or here, which is where i chose) but I can't seem to toggle the backpack with Enigma running, clicking in the right thumbstick does nothing until i disable Enigma

not really sure if this is fixable due to the nature of Enigma, but i'm just reporting it here in case there _is_ something you can do about it

**Comment by TheNexusAvenger** [comment]
In general, the downstream project is the right place to report incompatibilities, so this *is* the right place to report the problem.

This is most likely fixable because the [`InputBegan` event handling](https://github.com/TheNexusAvenger/Nexus-VR-Backpack/blob/f254633483b587190625c1c8ed2212a6b20d1c9e/src/CharacterBackpack.lua#L58) checks for `UserInputService:GetFocusedTextBox()` (which is always `true` because Enigma is spamming a `TextBox`). The Git blame suggests there was a reason for this, but I don't recall why. Regardless, I'll look into getting a fix out.

**Comment by TheNexusAvenger** [comment]
Fixed in V.1.1.0 and rolling out to new servers now.
